export const CHANGE_MESSAGE = 'CHANGE_MESSAGE';
export const INCREMENTAR_CONTADOR = 'INCREMENTAR_CONTADOR';
export const DECREMENTAR_CONTADOR = 'DECREMENTAR_CONTADOR';
export const CHANGE_DATOS_PERSONALES = 'CHANGE_DATOS_PERSONALES';