export const CAMBIA_MENSAJE = 'CAMBIA_MENSAJE';
export const INCREMENTA_CONTADOR = 'INCREMENTA_CONTADOR';
export const DECREMENTA_CONTADOR = 'DECREMENTA_CONTADOR';
export const CAMBIA_DATOS_PERSONALES = 'CAMBIA_DATOS_PERSONALES';